# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
  calendso:
    build:
      target: "base"
    restart: always
    ports:
      - 3000:3000
      - 5555:5555
    env_file: .env
    command: sh -c "npx prisma migrate reset --force && yarn db-seed && yarn dev"
    environment:
      - NODE_ENV=development
    depends_on:
      - db
volumes:
  database-data: